//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotDesktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceType
    {
        public int DeviceTypeId { get; set; }
        public string DeviceType1 { get; set; }
    }
}
