//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotDesktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int DeviceId { get; set; }
        public string DeviceNumber { get; set; }
        public string DeviceImage { get; set; }
        public int DeviceTypeId { get; set; }
        public int BookingStatusId { get; set; }
        public string DeviceDescription { get; set; }
        public bool IsActive { get; set; }
    }
}
