//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotDesktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workplace
    {
        public int WorkplaceId { get; set; }
        public string WorkplaceNumber { get; set; }
        public string WorkplaceImage { get; set; }
        public int BookingStatusId { get; set; }
        public string WorkplaceDescription { get; set; }
        public bool IsActive { get; set; }
    }
}
