//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotDesktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkplaceBooking
    {
        public int BookingId { get; set; }
        public string UserName { get; set; }
        public System.DateTime BookingFrom { get; set; }
        public System.DateTime BookingTo { get; set; }
        public int AssignWorkplaceId { get; set; }
    }
}
